import { VERSION } from '../version.js';

function toBase64Ascii(text) {
  if (typeof btoa === 'function') return btoa(text);
  return Buffer.from(text, 'ascii').toString('base64');
}

export function generateConsoleCode({ svg, layersJson, budget = 1280000 }) {
  const svgData = toBase64Ascii(svg);
  const layerData = toBase64Ascii(layersJson);
  return `// Generated by RAGE Emblem Codec v${VERSION}\n(() => {\n  const svgData = ${JSON.stringify(svgData)};\n  const layerData = ${JSON.stringify(layerData)};\n  const budget = ${Number(budget)};\n  const tokenEl = document.getElementsByName("__RequestVerificationToken")[0];\n  const hashEl = document.getElementById("editorField-hash");\n  if (!tokenEl || !hashEl) {\n    alert("RAGE Emblem Codec: Rockstar emblem editor token/hash not found. Open the Social Club emblem editor first.");\n    return;\n  }\n  const body = JSON.stringify({\n    crewId: "0",\n    emblemId: "",\n    parentId: "",\n    svgData,\n    layerData,\n    hash: hashEl.value\n  });\n  const actualBytes = new TextEncoder().encode(body).length;\n  if (actualBytes > budget) {\n    alert("RAGE Emblem Codec: request is " + actualBytes.toLocaleString() + " bytes, over the " + budget.toLocaleString() + " byte budget. Nothing was sent.");\n    return;\n  }\n  const request = new XMLHttpRequest();\n  request.open("POST", "/emblems/save", true);\n  request.onreadystatechange = function () {\n    if (request.readyState !== XMLHttpRequest.DONE) return;\n    let response;\n    try { response = JSON.parse(request.responseText); }\n    catch (e) { alert("Rockstar returned an unreadable response."); return; }\n    if (Number(response.Status) === 200) {\n      window.location.href = "https://socialclub.rockstargames.com/emblems/edit/" + response.EmblemId;\n    } else if (response.Message) {\n      alert(response.Message);\n    } else if (response.Error && response.Error.Message) {\n      alert(response.Error.Message);\n    } else {\n      alert("Rockstar rejected the emblem request.");\n    }\n  };\n  request.setRequestHeader("Content-Type", "application/json");\n  request.setRequestHeader("__RequestVerificationToken", tokenEl.value);\n  request.setRequestHeader("X-Requested-With", "XMLHttpRequest");\n  request.send(body);\n})();`;
}
